# Generated by Django 5.1.3 on 2025-03-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                ("region", models.CharField(max_length=255)),
                ("sub_region", models.CharField(max_length=255)),
                ("lat", models.DecimalField(decimal_places=5, max_digits=8)),
                ("lon", models.DecimalField(decimal_places=5, max_digits=8)),
            ],
            options={
                "db_table": "location",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MarineData",
            fields=[
                ("data_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                (
                    "sea_surface_temperature",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "hotspot_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "degree_heating_week",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
            ],
            options={
                "db_table": "marine_data",
                "managed": False,
            },
        ),
    ]
